
stages:
  - ver
  - init
  - test
  - deploy

ver:
  stage: ver
  script:
    - python3 --version
    - whoami

init:
  stage: init
  script:
    - apt-get update
    - apt-get -y install python3-pip
    - pip install -r requirements.txt

run_tests:
  stage : test
  script:
    - apk add postgresql-dev --no-cache
    - pip install psycopg2-binary
    - sh backend/application/test_requests.sh

deploy_staging:
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
    - echo "Deployed to Staging Server https://flask-api-staging.herokuapp.com"
  environment:
    name: staging
    url: https://flask-api-staging.herokuapp.com/


deploy_production:
  stage: deploy
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/flask-api-prod.git
    - git push heroku master
    - echo "Deployed to Production Server https://flask-api-prod.herokuapp.com"
  environment:
    name: production
    url: https://flask-api-prod.herokuapp.com/
  when: manual